version: "3.3"

services:
  settlement-service:
    image: "newbank/payment-settlement"
    container_name: "settlement-service"
    mem_limit: 1g
    cpus: 2
    ports:
      - 5008:8080
    environment:
      - TRANSACTION_WITH_PORT=${TRANSACTION_SERVICE}:8080
      - COSTUMER_WITH_PORT=${COSTUMER_SERVICE}:8080
      - EXTERNALBANK_WITH_PORT=${EXTERNAL_BANK_SERVICE}:8080
      - FEESCALCULATOR_WITH_PORT=${FEES_CALCULATOR_SERVICE}:8080
      - PAYMENTPROCESSOR_WITH_PORT=${PAYMENT_PROCESSOR_SERVICE}:8080
    networks:
      - spring-newbank-network

networks:
  spring-newbank-network:
    external: true