  route:
    group_by: [ 'job', 'severity' ]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h
    receiver: team-notifications

  receivers:
    - name: team-notifications
      webhook_configs:
      - url: https://discord.com/api/webhooks/1180630684390396024/_tPwW6cTfcT62uWBYVm-ZecXIRS99eGJEhRZz5zozVNrvMGwCnTtCK-xyFqUPsMj2561
