version: "3.3"

services:
  fees-calculator-service:
    image: "newbank/fees-calculator"
    container_name: "fees-calculator-service"
    cpus: 2

    restart: always
    env_file:
      - .env
    ports:
      - 5005:8080
    environment:
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - COSTUMER_WITH_PORT=${COSTUMER_SERVICE}:8080
      - POSTGRES_HOST=${POSTGRES_HOST}:5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network

networks:
  spring-newbank-network:
    external: true