version: '3.8'

services:
  business-integrator-service:
    restart: always
    image: "newbank/business-integrator"
    container_name: "business-integrator-service"
    mem_limit: 1g
    cpus: 2
    env_file:
      - .env
    ports:
      - "5012:8080"
    depends_on:
      integrator-db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=integrator-db:5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network

  integrator-db:
    image: postgres:15.2
    container_name: "integrator-db"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - spring-newbank-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  spring-newbank-network:
    external: true
