version: "3.3"

services:
  payment-service:
    image: "newbank/payment-processor"
    container_name: "payment-service"
    mem_limit: 1g
    ports:
      - 5004:8080
    environment:
      - CCN_WITH_PORT=${CCN_SERVICE}:8080
      - COSTUMER_WITH_PORT=${COSTUMER_SERVICE}:8080
      - EXTERNALBANK_WITH_PORT=${EXTERNAL_BANK_SERVICE}:8080
      - TRANSACTION_WITH_PORT=${TRANSACTION_SERVICE}:8080
      - CASSANDRA_HOST=transaction-db
    depends_on:
      - transaction-db
    restart: on-failure
    networks:
      - spring-newbank-network

  transaction-db:
    image: cassandra
    container_name: transaction-db
    networks:
      - spring-newbank-network

networks:
  spring-newbank-network:
    external: true