version: '3.1'
services:

  transactions-service:
    image: "newbank/transactions-service"
    container_name: "transactions-service"
    mem_limit: 1g
    cpus: 2
    ports:
      - "4999:8080"

    networks:
      - spring-newbank-network
    environment:
      - POSTGRES_HOST=postgres:5432

#  transaction-pg-db:
#    image: postgres
#    container_name: "transaction-pg-db"
#    mem_limit: 1g
#    cpus: 2
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=postgresuser
#      - POSTGRES_PASSWORD=postgrespass
#      - POSTGRES_DB=transaction-db
#    networks:
#      - spring-newbank-network




networks:
  spring-newbank-network:
    external: true
